"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, CalendarDays, MapPin, Users } from "lucide-react";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { EventStatusBadge, EventTypeBadge, SeverityBadge } from "@/components/ui/badge";
import { PageHeader, StatCard } from "@/components/ui/page";
import { formatDateTime } from "@/lib/utils";
import { toast } from "@/components/ui/toast";
import type { DisasterEventResponse, EventStatus } from "@/lib/types";
export default function NgoEventDetailPage() { const { id } = useParams<{ id: string }>(); const router = useRouter(); const [event, setEvent] = useState<DisasterEventResponse | null>(null); useEffect(() => { api<DisasterEventResponse>(`/api/v1/events/${id}`).then(setEvent).catch(() => {}); }, [id]); async function status(value: EventStatus) { try { const next = await api<DisasterEventResponse>(`/api/v1/events/${id}/status?status=${value}`, { method: "PATCH" }); setEvent(next); toast("success", `Event ${value.toLowerCase()}.`); } catch (e: any) { toast("error", "Could not update event", e.message); } } if (!event) return <div className="text-sm text-mist">Loading event…</div>; return <div><button onClick={() => router.back()} className="mb-5 inline-flex items-center gap-2 text-sm text-mist hover:text-ink"><ArrowLeft className="h-4 w-4" /> Back to events</button><PageHeader title={event.title} description={event.description || "Disaster response event."} actions={<div className="flex gap-2">{event.status === "OPEN" && <Button onClick={() => status("ONGOING")}>Start event</Button>}{event.status === "ONGOING" && <Button variant="secondary" onClick={() => status("CLOSED")}>Close event</Button>}</div>} /><div className="flex flex-wrap gap-2 mb-6"><EventStatusBadge status={event.status} /><EventTypeBadge type={event.type} /><SeverityBadge severity={event.severity} /></div><div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-8"><StatCard label="Volunteers joined" value={event.participantCount} hint={`${event.requiredVolunteers} needed`} /><StatCard label="Event owner" value={event.organizerName} hint="Read-only participant view" /><StatCard label="Starts" value={formatDateTime(event.startAt)} /></div><div className="nx-card space-y-4 text-sm text-mist"><div className="flex items-center gap-3"><MapPin className="h-4 w-4 text-signal" />{event.divisions.map((d) => d.name).join(", ") || "Bangladesh"}</div><div className="flex items-center gap-3"><CalendarDays className="h-4 w-4 text-signal" />{formatDateTime(event.startAt)} → {formatDateTime(event.endAt)}</div><div className="flex items-center gap-3"><Users className="h-4 w-4 text-signal" />Volunteers can join or withdraw from their dashboard. Participant identities are not exposed here.</div></div></div>; }
